### ISSUE TITLE
Negative timestamps do not work

### ISSUE THREAD

**Issue by sebdg** [kairosdb/kairosdb#186] opened 2015-06-13 16:14 UTC
Very easy to reproduce in fact

curl -XPOST http://127.0.0.1:8080/api/v1/datapoints -d '[
{"name":"stocks.volumes", "datapoints":[[-86400000,283200],[-172800000,225600]],
 "tags":{"column":"volume","symbol":"AA","exchange":"NYSE","sector":"3","industry":"144"}}
]

this -86400000 should be 31/12/1969 00:00:00 but that returns errors as 
{"errors":["metric[0](name=stocks.volumes).datapoints[0].value cannot be null or empty, must be greater than or equal to 1."}

Something that would make it easier to lookup errors when sending a batch is that the 'indexes of datapoints[xx] would correspond to reality. (looks as a regression from what I deduce from other posts)
In this 2 points cas the full result is : 

{"errors":[
   "metric[0](name=stocks.volumes).datapoints[0].value cannot be null or empty, must be greater than or equal to 1.",
   "metric[0](name=stocks.volumes).datapoints[0].value cannot be null or empty, must be greater than or equal to 1."]
}

https://github.com/kairosdb/kairosdb/issues/47

**Comment by brianhks** [comment] 2015-06-13 19:12
Are you using 1.0 kairis?

**Comment by sebdg** [comment] 2015-06-13 19:24
I've used a fresh build from the repo even switched to dev branch.
Can i get the version at runtime ?
the packages that i've build are named 1.0.0 and 1.0.0 SNAPSHOT.

**Comment by brianhks** [comment] 2015-06-14 22:07
api/v1/version gives you the running version.

I've got tests in DatastoreTestHelper that inserts and queries negative values.  Looks like the problem is in the json validator, it still won't accept negative values :(

**Comment by jsabin** [comment] 2015-06-17 13:44
Fixed in d047dc97cd5a8337e86190286b5829bcb126a137 (push metrics with negative time stamps) and 033c1eba773bbb9eaf54e340f2bc6ef00b92d03e (query metrics with negative time stamps)

**Closed by jsabin** 2015-06-17 13:44 UTC
Labels: bug
