### ISSUE TITLE
Incredibly high (inaccurate) values reported

### ISSUE THREAD

**Issue by arussellsaw** [kairosdb/kairosdb#166] opened 2015-04-16 14:36 UTC
after updating to 0.9.5-beta2 on one of our ten ingest nodes, we saw this node reporting ludicrously high values, in the sextillion range, for metrics that should be reporting in the hundreds, also all tags that we apply to our metrics were not present on these high values. the config was the same as we used for 0.9.4, though the kairosdb.datapoint,factory values were later added to see if the lack of that config was the cause (it was not).

**Comment by FrEaKmAn** [comment] 2015-04-16 18:11
How do you insert values? Are we talking about correct number + a lot of zeros or totally incorrect values?

**Comment by arussellsaw** [comment] 2015-04-16 18:21
We ingest via telnet, with about 5-10 tags on each metric. The values
weren't all zeroes, but partially, starts with non zero values, then a
block of zeroes, then values again, then more zeroes, I'll post some of the
actual values later.

**Comment by arussellsaw** [comment] 2015-04-17 07:21
one of the actual values i'm seeing, they're all similar to this: 4644753179070305000. similar in structure, but varying in value anywhere from the low quintillions up to mid sextillions.

**Comment by arussellsaw** [comment] 2015-04-17 14:27
could the fact that we were writing on a 0.9.5-beta2 node, but querying from a 0.9.4 node cause this? i did not apply the update to our query nodes, as we mostly want this fix for the write consistency changes.

**Comment by warmans** [comment] 2015-04-17 16:07
I can reproduce this by ingesting values on 9.5b2 then querying with 9.4. Querying the same data with 9.5b2 will return correct results.

**Comment by brianhks** [comment] 2015-04-17 20:34
Wow this is crap.  You shouldn't run into this kind of problem.

Can you post the values you were inserting into 9.5, I'd like to test this out.

**Comment by warmans** [comment] 2015-04-20 08:24
I've not re-tested with these exact values but they are representative of the values that showed the issue: 

{"timestamp":1429517677510,"name":"system.disk.usage.used","value":54240256.0,"tags":{"function":"proxy","datacenter":"DC1","mount_point":"/boot","state":"Production","adserver":"ANON","host":"anon.anon.com","serverid":"ANON1","physical":"HOST1"}}
{"timestamp":1429517677511,"name":"system.disk.usage.free","value":427289600.0,"tags":{"function":"proxy","datacenter":"DC1","mount_point":"/boot","state":"Production","adserver":"ANON","host":"anon.anon.com","serverid":"ANON1","physical":"HOST1"}}
{"timestamp":1429517677511,"name":"system.disk.usage.percent","value":10.7,"tags":{"function":"proxy","datacenter":"DC1","mount_point":"/boot","state":"Production","adserver":"ROIMEDIA","host":"anon.anon.com","serverid":"ANON1","physical":"HOST1"}}
{"timestamp":1429517677511,"name":"system.cpu.percent","value":3.778337530274787,"tags":{"function":"proxy","datacenter":"DC1","host":"anon.anon.com","serverid":"ANON1","state":"Production","adserver":"ANON","physical":"HOST1"}}
{"timestamp":1429517677511,"name":"system.cpu.idle","value":95.46599496836205,"tags":{"function":"proxy","datacenter":"DC1","host":"anon.anon.com","serverid":"ANON1","state":"Production","adserver":"ANON","physical":"HOST1"}}

**Comment by brianhks** [comment] 2015-04-20 18:18
I'm having a hard time reproducing this problem.  On my desktop using a single node 2.0.11 Cassandra cluster I inserted the data with the latest dev code.  I then queried it with the latest 0.9.4 release.  I inserted the data using telnet as well as http.  I'm querying it with the Kairos UI.

As a secondary test I pointed a 0.9.4 Kairos at a cluster I've been loading system telemetry into using 0.9.5 beta 1.  I was able to read both load and cpu value data just fine.

It looks like we have a problem as two of you have seen it.  I'm just not sure how to expose it.

**Comment by warmans** [comment] 2015-04-20 19:56
Hmm, weird. I'll check my test VM tomorrow for cassandra version etc. I was
running a two node Cassandra cluster (on the same VM with different ports
configured) but otherwise everything should've been the same as your test.
I'll run some more tests and see if I can narrow down the issue.

**Comment by warmans** [comment] 2015-04-21 08:24
Here is a detailed description of my test setup (running on Virtualbox): 

- Centos (6.6)
- OpenJDK (1.7)
- Single cassandra node with default configuration (2.1.2)
- Two kairosdb instances. One at 94 and one at 95.

Data:

```
{"timestamp":1429517677510,"name":"system.disk.usage.used","value":54240256.0,"tags":{"function":"proxy","datacenter":"DC1","mount_point":"/boot","state":"Production","adserver":"ANON","host":"anon.anon.com","serverid":"ANON1","physical":"HOST1"}}
{"timestamp":1429517677511,"name":"system.disk.usage.free","value":427289600.0,"tags":{"function":"proxy","datacenter":"DC1","mount_point":"/boot","state":"Production","adserver":"ANON","host":"anon.anon.com","serverid":"ANON1","physical":"HOST1"}}
{"timestamp":1429517677511,"name":"system.disk.usage.percent","value":10.7,"tags":{"function":"proxy","datacenter":"DC1","mount_point":"/boot","state":"Production","adserver":"ANON","host":"anon.anon.com","serverid":"ANON1","physical":"HOST1"}}
{"timestamp":1429517677511,"name":"system.cpu.percent","value":3.778337530274787,"tags":{"function":"proxy","datacenter":"DC1","host":"anon.anon.com","serverid":"ANON1","state":"Production","adserver":"ANON","physical":"HOST1"}}
{"timestamp":1429517677511,"name":"system.cpu.idle","value":95.46599496836205,"tags":{"function":"proxy","datacenter":"DC1","host":"anon.anon.com","serverid":"ANON1","state":"Production","adserver":"ANON","physical":"HOST1"}}
{"timestamp":1429517687510,"name":"system.disk.usage.used","value":54240256.0,"tags":{"function":"proxy","datacenter":"DC1","mount_point":"/boot","state":"Production","adserver":"ANON","host":"anon.anon.com","serverid":"ANON1","physical":"HOST1"}}
{"timestamp":1429517687511,"name":"system.disk.usage.free","value":427289600.0,"tags":{"function":"proxy","datacenter":"DC1","mount_point":"/boot","state":"Production","adserver":"ANON","host":"anon.anon.com","serverid":"ANON1","physical":"HOST1"}}
{"timestamp":1429517687511,"name":"system.disk.usage.percent","value":10.7,"tags":{"function":"proxy","datacenter":"DC1","mount_point":"/boot","state":"Production","adserver":"ANON","host":"anon.anon.com","serverid":"ANON1","physical":"HOST1"}}
{"timestamp":1429517687511,"name":"system.cpu.percent","value":3.778337530274787,"tags":{"function":"proxy","datacenter":"DC1","host":"anon.anon.com","serverid":"ANON1","state":"Production","adserver":"ANON","physical":"HOST1"}}
{"timestamp":1429517687511,"name":"system.cpu.idle","value":95.46599496836205,"tags":{"function":"proxy","datacenter":"DC1","host":"anon.anon.com","serverid":"ANON1","state":"Production","adserver":"ANON","physical":"HOST1"}}
{"timestamp":1429517697511,"name":"system.disk.usage.free","value":427289600.0,"tags":{"function":"proxy","datacenter":"DC1","mount_point":"/boot","state":"Production","adserver":"ANON","host":"anon.anon.com","serverid":"ANON1","physical":"HOST1"}}
{"timestamp":1429517697511,"name":"system.disk.usage.percent","value":10.7,"tags":{"function":"proxy","datacenter":"DC1","mount_point":"/boot","state":"Production","adserver":"ANON","host":"anon.anon.com","serverid":"ANON1","physical":"HOST1"}}
{"timestamp":1429517697511,"name":"system.cpu.percent","value":3.778337530274787,"tags":{"function":"proxy","datacenter":"DC1","host":"anon.anon.com","serverid":"ANON1","state":"Production","adserver":"ANON","physical":"HOST1"}}
{"timestamp":1429517697511,"name":"system.cpu.idle","value":95.46599496836205,"tags":{"function":"proxy","datacenter":"DC1","host":"anon.anon.com","serverid":"ANON1","state":"Production","adserver":"ANON","physical":"HOST1"}}
```

I ingest this into the kairos95 instance via telnet (https://github.com/swco/kairosdb-streamer). 

Now I query the data using the kairos interface with both versions. 

94 Produces: 
```
{"queries":[{"sample_size":3,"results":[{"name":"system.cpu.idle","group_by":[{"name":"type","type":"number"}],"tags":{"adserver":["ANON"],"datacenter":["DC1"],"function":["proxy"],"host":["anon.anon.com"],"physical":["HOST1"],"serverid":["ANON1"],"state":["Production"]},"values":[[1429517677511,95.465995],[1429517687511,95.465995],[1429517697511,95.465995]]}]}]}
```

95 for the same query produces: 

```
{"queries":[{"sample_size":3,"results":[{"name":"system.cpu.idle","tags":{"\u0000\rkairos_doubleadserver":["ANON"],"datacenter":["DC1"],"function":["proxy"],"host":["anon.anon.com"],"physical":["HOST1"],"serverid":["ANON1"],"state":["Production"]},"values":[[1429517677511,4.6364182391166915E18],[1429517687511,4.6364182391166915E18],[1429517697511,4.6364182391166915E18]]}]}]}
```

I'm going to try varying the cassandra version (2.0) and if that doesn't help I'll try oracle java instead of openJDK.

**Comment by lcoulet** [comment] 2015-04-21 12:37
It is probably not related, but as far as I can tell Cassandra is not
recommended with OpenJDK, and not supported for datastax distribution. The
problem is probably not related to Cassandra or Java version.

Extract from Apache Cassandra documentation:
"Cassandra requires the most stable version of Java 7 or 8 you can deploy,
preferably the Oracle/Sun JVM
<http://www.oracle.com/technetwork/java/javase/downloads/index.html>."

Extract from DSC installation instructions for Cassandra 2.1:
"You must configure your operating system to use the Oracle JRE, not the
OpenJDK. The latest 64-bit version of Java 7 is recommended. The minimum
supported version is 1.7.0_25."


2015-04-21 8:24 GMT+00:00 Stefan Warman <notifications@github.com>:

**Comment by warmans** [comment] 2015-04-21 12:59
Yeah we do not run openjdk on any production servers (which also had this mysterious issue). I also ran the test with oracle java in addition to openjdk.

**Comment by brianhks** [comment] 2015-04-21 20:18
I wasn't able to get your go script to work - mostly because I don't know how to use go.  I put the data into a bash script to send it off

`#!/bin/bash

host=localhost
port=4243

echo "put system.cpu.idle 1429517677511 95.46599496836205 function=proxy datacenter=DC1 host=anon.anon.com serverid=ANON1 state=Production adserver=ANON physical=HOST1" | nc -w 30 $host $port
echo "put system.cpu.idle 1429517677511 95.46599496836205 function=proxy datacenter=DC1 host=anon.anon.com serverid=ANON1 state=Production adserver=ANON physical=HOST1" | nc -w 30 $host $port
echo "put system.cpu.idle 1429517677511 95.46599496836205 function=proxy datacenter=DC1 host=anon.anon.com serverid=ANON1 state=Production adserver=ANON physical=HOST1" | nc -w 30 $host $port`

I inserted the data and was able to read it just fine in both the 9.4 and 9.5 UI's.  Try inserting the data with my bash script to see if it makes a difference.

**Comment by warmans** [comment] 2015-04-22 08:09
Hi brian, 

I've cleaned out my db. Restarted all the serices and ran the import into 9.5 with your script. The results are the same: 

9.4
```
{"queries":[{"sample_size":1,"results":[{"name":"system.cpu.idle","tags":{"\u0000\rkairos_doubleadserver":["ANON"],"datacenter":["DC1"],"function":["proxy"],"host":["anon.anon.com"],"physical":["HOST1"],"serverid":["ANON1"],"state":["Production"]},"values":[[1429517677511,4.6364182391144643E18]]}]}]}
```

9.5
```
{"queries":[{"sample_size":1,"results":[{"name":"system.cpu.idle","group_by":[{"name":"type","type":"number"}],"tags":{"adserver":["ANON"],"datacenter":["DC1"],"function":["proxy"],"host":["anon.anon.com"],"physical":["HOST1"],"serverid":["ANON1"],"state":["Production"]},"values":[[1429517677511,95.46599496836205]]}]}]}
```

**Comment by brianhks** [comment] 2015-04-22 15:35
Is by any chance your machine not set with English as the default?

**Comment by warmans** [comment] 2015-04-22 15:41
Shouldn't be. `locale` gives me: 

LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=

**Comment by brianhks** [comment] 2015-04-22 16:05
Have you tried inserting this data using http?  If you surround your data file with [ and ] and then put commas on each line you can then use this script to post the data to Kairos
```bash
#!/bin/bash

host=localhost:8080

curl --data-binary @$1 --header "Content-Type: application/json" http://$host/api/v1/datapoints
```
The parameter to the script is your file to send.

**Comment by warmans** [comment] 2015-04-22 20:02
I have indeed. The only thing left that I can think to try is a different
OS (ubuntu or centos 7).Are you testing on a more modern 64bit linux than
centos 6?

**Comment by brianhks** [comment] 2015-04-22 20:13
Are you sure you are running 9.4?  This looks like a result from 9.3.

**Comment by warmans** [comment] 2015-04-22 20:39
Oh that's interesting. The RPM I used had 9.4 in the name but we have built custom RPMs in the past so it it's at least possible that it's actually an older version. I'll verify the RPM matches the one on the releases page first thing tomorrow.

**Comment by brianhks** [comment] 2015-04-22 20:42
There was a change from 9.3 to 9.4 that was not backwards compatible.  We started adding data type tags into the row key, the /0000/rkairos_double is the result of the old code interpreting that as a tag.

Switching from 9.3 to a later version is a one way trip.  The new code will read old data but not the other way round.

**Comment by warmans** [comment] 2015-04-22 21:08
So the version reported by our instances is `KairosDB 0.9.4.20140225101340`
However I recall that the RPM is `9.4-1` not `9.4-6` so I guess we must have built it from a version that did not include the new tag types (or downloaded an earlier release if one was posted - I don't remember). 

It's looking like the mystery is solved. I'll re-download a fresh 9.4 RPM and re-run my tests.
.

**Comment by warmans** [comment] 2015-04-23 08:59
Re-tested with latest 9.4 - works fine. So yeah this is actually a 9.3 -> 9.5 issue. Feel free to close the issue and apologies for the confusion. No idea how we ended up with a non-standard 9.3 version labelled as 9.4.

**Closed** 2015-04-23 15:33 UTC
Labels: bug
