### ISSUE TITLE
Potential failure when storing String datatype

### ISSUE THREAD

**Issue by hippoandy** [kairosdb/kairosdb#426] opened 2018-02-02 02:05 UTC
Dear Author,

I tried to store the date in the string type, and a data looks like this:
`ver_format=3,fmt_opt=1,app=AirBox,ver_app=0.35.0,device_id=74DA3895C5C0,tick=1517536368,date=2018-02-02,time=09:52:48,device=tses,s_0=178,s_1=100,s_2=1,s_3=0,s_d0=7,s_d1=8,s_d2=5,s_t0=17,s_h0=83,gps_lat=24.06,gps_lon=120.696,gps_fix=1,gps_num=9,gps_alt=2"`

However, when I query the data out, I got the follwoing:
"values": [
			[1517536201000, "ver_format=3,fm"],
			[1517536203000, "ver_for"],
			[1517536205000, "ver_fo"],
			[1517536208000, "ver_format"],
			[1517536209000, "ver_fo"],
			[1517536209000, "ver_for"],
			[1517536210000, "ver_format=3"],
			[1517536213000, "ver_forma"],
			[1517536214000, "ver_f"],
			[1517536216000, "ver"],
			[1517536217000, "ver_fo"],
			[1517536219000, "ver"],
			[1517536220000, "ver_fo"],
			[1517536221000, "ver"],
			[1517536223000, "v"],
			[1517536223000, "ver_fo"],

It seems like the string is not fully stored in the database.

I confirmed that my insert query is correct, which looks like:
`[{'tags': {'SiteName': 'taichung99', 'device': 'Taichung99', 'app': 'AirBox', 'device_id': '74DA3895C55A'}, 'type': 'string', 'name': 'AirBox.AllData', 'datapoints': [[1494470190000.0, 'ver_format=3,fmt_opt=1,app=AirBox,ver_app=0.35.0,device_id=74DA3895C55A,tick=1494470190,date=2017-05-11,time=10:36:30,device=Taichung99,s_0=1621,s_1=100,s_2=1,s_3=0,s_d0=47,s_d1=62,s_d2=33,s_t0=32.25,s_h0=73,gps_lat=24.308,gps_lon=120.704,gps_fix=1,gps_num=9,gps_alt=2']]}]`

Do you have any suggestion what might be going wrong? Thank you!

**Comment by brianhks** [comment] 2018-02-02 04:16
Here is a simple test I wrote:

    #!/bin/bash
    
    now=$(($(date +%s%N)/1000000))
    metric=string_insert
    host=localhost:8080
    
    data="[{\"name\":\"$metric\",\"tags\":{\"host\":\"A\"},\"datapoints\":[[$now,\"ver_format=3,fmt_opt=1,app=AirBox\"]]}]"
    
    echo "$data"
    curl -X POST --data "$data" --header "Content-Type: application/json" http://$host/api/v1/datapoints

When I then queried the data I got:

    {"queries":[{"sample_size":1,"results":[{"name":"string_insert","group_by":[{"name":"type","type":"text"}],"tags":{"host":["A"]},"values":[[1517544372785,"ver_format=3,fmt_opt=1,app=AirBox"]]}]}]}

That seems to work.  What are you using as a client?  Maybe the client app is removing the quotes or doing some interpretation before sending it to kairos.

**Comment by hippoandy** [comment] 2018-02-02 04:24
The client I am using is this one:
python-kairosdb
http://python-kairosdb.readthedocs.io/en/latest/index.html

I checked the code of this lib. I just like an interface for us to call the python requests lib. functions.

**Comment by brianhks** [comment] 2018-02-02 04:27
Hmm, my guess is that python or the library is doing some extra interpretation of that string.  Not sure if it makes a difference but you could try to use double quotes on the string instead of single quotes.

**Comment by hippoandy** [comment] 2018-02-02 04:31
But the same script works for KairosDB 1.1.3. Now for 1.2, sometimes it works, sometimes the string seems to be cut off. My and my colleague are still verifying whether if the data source has an error.

**Comment by brianhks** [comment] 2018-02-02 04:39
Do a packet trace and make sure what it is putting on the wire is the same.  You can also verify with my shell script I pasted to see if it works.  I don't know why it would have changed in 1.2

**Comment by hippoandy** [comment] 2018-02-02 05:12
Hi, I did the packet trace using tshark. The content is:
`<field name="http.file_data" showname="File Data: 483 bytes" size="483" pos="335" show="[{&quot;tags&quot;: {&quot;SiteName&quot;: &quot;\u53f0\u4e2d\u5e02\u967d\u660e\u570b\u5c0f&quot;, &quot;device&quot;: &quot;ymies&quot;, &quot;app&quot;: &quot;AirBox2&quot;, &quot;device_id&quot;: &quot;74DA3895C52C&quot;}, &quot;type&quot;: &quot;string&quot;, &quot;name&quot;: &quot;AirBox2.AllData&quot;, &quot;datapoints&quot;: [[1517547953000.0, &quot;ver_format=3,fmt_opt=1,app=AirBox,ver_app=0.35.0,device_id=74DA3895C52C,tick=1517547953,date=2018-02-02,time=13:05:53,device=ymies,s_0=168,s_1=100,s_2=1,s_3=0,s_d0=29,s_d1=32,s_d2=22,s_t0=16.25,s_h0=100,gps_lat=24.221,gps_lon=120.632,gps_fix=1,gps_num=9,gps_alt=2&quot;]]}]" value="5b7b2274616773223a207b22536974654e616d65223a20225c75353366305c75346532645c75356530325c75393637645c75363630655c75353730625c7535633066222c2022646576696365223a2022796d696573222c2022617070223a2022416972426f7832222c20226465766963655f6964223a2022373444413338393543353243227d2c202274797065223a2022737472696e67222c20226e616d65223a2022416972426f78322e416c6c44617461222c202264617461706f696e7473223a205b5b313531373534373935333030302e302c20227665725f666f726d61743d332c666d745f6f70743d312c6170703d416972426f782c7665725f6170703d302e33352e302c6465766963655f69643d3734444133383935433532432c7469636b3d313531373534373935332c646174653d323031382d30322d30322c74696d653d31333a30353a35332c6465766963653d796d6965732c735f303d3136382c735f313d3130302c735f323d312c735f333d302c735f64303d32392c735f64313d33322c735f64323d32322c735f74303d31362e32352c735f68303d3130302c6770735f6c61743d32342e3232312c6770735f6c6f6e3d3132302e3633322c6770735f6669783d312c6770735f6e756d3d392c6770735f616c743d32225d5d7d5d"/>`

The packet has complete data. However, when I use the web UI to query the result is:
`[{
	"sample_size": 1,
	"results": [{
		"name": "AirBox2.AllData",
		"group_by": [{
			"name": "type",
			"type": "text"
		}],
		"tags": {
			"SiteName": ["台中市陽明國小"],
			"app": ["AirBox2"],
			"device": ["ymies"],
			"device_id": ["74DA3895C52C"]
		},
		"values": [
			[1517547953000, "ver_for"]
		]
	}]
}]`

Any idea?

**Comment by hippoandy** [comment] 2018-02-02 07:20
Is there any limit in string length? I noticed that if the string is too long (maybe longer than 255 chars) the data will be lost.

**Comment by brianhks** [comment] 2018-02-02 13:56
The limit as far as I know is really big.  Can you post your python script so I can test it?

**Comment by hippoandy** [comment] 2018-02-03 01:19
`````
import paho.mqtt.client as mqtt
import os
import re
import json
import sys
reload( sys )
sys.setdefaultencoding( 'utf-8' )
import math
import requests
from datetime import datetime
from datetime import timedelta
import time
import kairosdb

MQTT_SERVER = "gpssensor.ddns.net"
MQTT_TOPIC = "LASS/Test/#"
MQTT_PORT = 1883
MQTT_ALIVE = 60
KairosDB_URL = 'http://127.0.0.1:8080'
LASS_REQ_VERFORMAT = 2.0
def on_connect(client, userdata, flags, rc):
	client.subscribe( MQTT_TOPIC )
def on_disconnect(client, userdata, rc):
    if rc != 0:
        print "Unexpected MQTT disconnection. Will auto-reconnect"
def on_message(client, userdata, msg):
	re.sub('\s+','',msg.payload)
	items = re.split('\|',msg.payload)
	all_value = ""
	LASS_DATE = ""
	LASS_TIME = ""
	data = [{
		"name": 'Metric',
		"type": "string",
		"datapoints": [[ {},{} ]],
	}]
	for item in items:
		if item == '':
			continue
		pairs = re.split('=',item)
		if len(pairs)==1:
			continue
		if (pairs[0] == "time"):
			LASS_TIME = pairs[1]
		elif (pairs[0] == "date"):
			LASS_DATE = pairs[1]
		all_value = all_value + str(pairs[ 0 ]) + '=' + str(pairs[ 1 ]).replace( '\r', '' ).replace( '\n', '' ).replace( '\t', '' ) + ','
	try:
		timestamp = datetime.strptime( LASS_DATE + " " + LASS_TIME, '%Y-%m-%d %H:%M:%S' )
		timestamp = time.mktime( timestamp.timetuple() )
		timestamp = timestamp * 1000
	except: return
	data[ 0 ][ 'name' ] = 'LASS.Test'
	data[ 0 ][ 'datapoints' ][ 0 ][ 0 ] = timestamp
	data[ 0 ][ 'datapoints' ][ 0 ][ 1 ] = all_value[:-1]
	try:
		kdb_client.post( path=KairosDB_URL, data=data )
	except:
		pass
kdb_client = kairosdb.client.KairosDBAPIClient( api_endpoint=KairosDB_URL )
kdb_api = kairosdb.KairosDBAPI( kdb_client )
mqtt_client = mqtt.Client()
mqtt_client.on_connect = on_connect
mqtt_client.on_disconnect = on_disconnect
mqtt_client.on_message = on_message
mqtt_client.connect(MQTT_SERVER, MQTT_PORT, MQTT_ALIVE)
mqtt_client.loop_forever()
`````

please check, thank you so much!

**Comment by brianhks** [comment] 2018-02-03 06:16
When debugging these kinds of situations you must remove as many variables as you can from your code.  Make something simple and reproducible to test with.  Like this:

    import os
    import re
    import json
    import sys
    reload( sys )
    sys.setdefaultencoding( 'utf-8' )
    import math
    import requests
    from datetime import datetime
    from datetime import timedelta
    import time
    import kairosdb
    
    KairosDB_URL = 'http://127.0.0.1:8080/api/v1/datapoints'
    
    kdb_client = kairosdb.client.KairosDBAPIClient( api_endpoint=KairosDB_URL )
    kdb_api = kairosdb.KairosDBAPI( kdb_client )
    
    data = [{
    	"name": 'Metric',
    	"tags": { "host": "A" },
    	"type": "string",
    	"datapoints": [[ {},{} ]],
    }]
    
    all_value = "ver_format=3,fmt_opt=1,app=AirBox,ver_app=0.35.0,device_id=74DA3895C5C0,tick=1517536368,date=2018-02-02,time=09:52:48,device=tses,s_0=178,s_1=100,s_2=1,s_3=0,s_d0=7,s_d1=8,s_d2=5,s_t0=17,s_h0=83,gps_lat=24.06,gps_lon=120.696,gps_fix=1,gps_num=9,gps_alt=2"
    
    timestamp = int(round(time.time() * 1000))
    data[ 0 ][ 'name' ] = 'LASS.Test'
    data[ 0 ][ 'datapoints' ][ 0 ][ 0 ] = timestamp
    data[ 0 ][ 'datapoints' ][ 0 ][ 1 ] = all_value[:-1]
    print(kdb_client.post( path=KairosDB_URL, data=data ))

The above code will write your big string to kairos.  Best part is that it works.  This shows that the problem is not with Kairos or the python client, but most likely your code.  Sorry I'm not a python expert but my guess is that the way you build your string value python is doing some extra interpretation on the data.

**Comment by hippoandy** [comment] 2018-02-06 00:08
Okay, I will continue trying to modify the code to make it cleaner. I will not close this issue first. If the problem still exists, I will reopen it.

Thank you so much for your help! :-)

**Comment by hippoandy** [comment] 2018-02-08 03:16
Hi, I'm still getting this issue, and I'm sure that if I make the string's length < 255, the string could be inserted. the data I gave you is 254 length. Could you help me try to insert this one into your testbed?

`
ver_format=3,fmt_opt=1,app=AirBox,ver_app=0.35.0,device_id=74DA3895C5C0,tick=1517536368,date=2018-02-02,time=09:52:48,device=tses,s_0=178,s_1=100,s_2=1,s_3=0,s_d0=7,s_d1=8,s_d2=5,s_t0=17,s_h0=83,gps_lat=24.06,gps_lon=120.696,gps_fix=1,gps_num=9,gps_alt=2xxxxxxxxxxxxxxxx
`

It's about 270 char long. Thanks in advance!

**Comment by brianhks** [comment] 2018-02-08 23:40
Yup, something is amiss there.  I was able to reproduce it with a longer string.  It looks to be truncating the string :(

Thanks for your persistence.

**Comment by hippoandy** [comment] 2018-02-08 23:58
So, could you suggest me about the data insertion section of the KairosDB code?
Maybe I could help take a look as well and see where goes wrong. :-)

**Comment by brianhks** [comment] 2018-02-09 20:22
Found the problem and it is checked into develop.

**Comment by gucharbon** [comment] 2018-02-23 15:40
What's the status of this issue as of today ?

**Comment by brianhks** [comment] 2018-02-23 16:29
Fixed and in the develop branch.  This weekend I'm going to go over the other open issues and then cut a 1.2.1 release with bug fixes.

**Closed by brianhks** 2018-02-23 16:29 UTC

**Comment by lewisdiamond** [comment] 2018-03-05 02:22
Any news on 1.2.1? I'm having the same truncated string issue. I'm storing stringified JSON.

**Comment by lewisdiamond** [comment] 2018-03-06 01:44
FYI. 1.2.1 currently breaks on ScyllaDB. See https://github.com/scylladb/scylla/issues/3256

I don't know if you support it though.

**Comment by brianhks** [comment] 2018-03-06 13:37
I knew the range delete didn't work on their code.  I added code to work around that in 1.2, I wonder if it broke in the develop branch.  The string issue is a pretty big deal, I'll run the beta code through some tests this week and build 1.2.1 by next week.
